name: Snake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/GameTest.cpp'

jobs:
  snake_job:
    runs-on: ubuntu-latest
    name: Snake Job
    steps:
      - uses: actions/checkout@v2
      - name: update
        run: sudo apt-get update
      - name: install sdl2
        run: sudo apt install libsdl2-dev
      - name: install sdl2image
        run: sudo apt install libsdl2-image-dev
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: configure privelige
        run: chmod +x configure
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make test
        run: make test
